### PR TITLE
Add typings to the codebase

### PR DESCRIPTION
**Pull request by paroxp**
There are currently no typings available for this plugin. This is a
quick handcrafted attempt to adding them into the system.

The downside is, that these will need to be maintained manually, as the
codebase is JS at the moment.

### CODE REVIEW

**Comment by Izhaki** [comment]
I like this! And I'll be more than happy to merge.

But wouldn't a proper solution to this will be to contribute these under the `nodemon` repo and re-export here?

I've logged an issue on `nodemon` - https://github.com/remy/nodemon/issues/1679

**Comment by Izhaki** [comment]
I also wonder was done because:

- You `webpack.config.ts` is typed.
- For IDE auto-completion / contextual help.

?

**Comment by paroxp** [comment]
Yeah, I have my webpack configuration written up in TypeScript :) That being the case IDE is the next in line :D

I see what you mean, I presumed the plugin had it's own configuration.

There is this: https://www.npmjs.com/package/@types/nodemon

Which provides the types for the `nodemon` itself. That means I should be able to reduce the footprint of my contribution and make it easier to maintain in the future? But something will still need to exist to say `NodemonPlugin` is a `webpack.plugin` and accepts `NodemonSettings`.

Would that be cool?

Force push on the way.

**Comment by Izhaki** [comment]
I'll merge it tonight. Maybe, just maybe if I'm brave I'll add a test for it before.

**Comment by Izhaki** [comment]
Wow. Thank you so much - might not seem like a lot, but is of huge value!

**Pull request closed without merging**
