### PR TITLE
Upgrading `nodemon` to `1.18.10` for changes to Windows 10 support.

### PR DESCRIPTION
**Pull request by grmartin**
Matches: https://github.com/remy/nodemon/releases/tag/v1.18.10 fixing a heavy handed restart issue as well as a Windows 10 Last Access Date issue.

### CODE REVIEW

**Comment by Izhaki** [comment]
Thank you so much!

I'll be releasing a new version to npm tonight.

**Comment by Izhaki** [comment]
Hmmm....

Quite a few security issues after merge.

image

**Comment by grmartin** [comment]
Interesting... Did i slip up in my PR? (Sorry, a bit of a yarn newb)

**Comment by Izhaki** [comment]
No idea.

I'm reverting and will try the same tonight.

(to be honest, the yarn changes seemed somewhat inflated, but upon quick further inspection I couldn't see anything fundamentally wrong).

**Comment by Izhaki** [comment]
OK. I reverted ad the errors still show.

Will investigate later.

**Comment by Izhaki** [comment]
So. Turns out this is a new github feature. Nothing to do with your PR.

Anyhow, just released 4.0.8, which includes this.

Thanks again for this!

**Comment by grmartin** [comment]
Fancy. And GTK. And TY!

**Pull request merged**
