### PR TITLE
Ensure server stops when compilation is broken

### PR DESCRIPTION
**Pull request by cellis**
* This should stop the server when e.g. Typescript is broken

* Was working on this last night but couldn't get the package to link locally ( or from my branch using `yarn install <git url>`. Testing with https://github.com/cellis/typescript-babel-webpack-server

### CODE REVIEW

**Comment by cellis** [comment]
@Izhaki just opened PR. See details!

**Comment by Izhaki** [comment]
I will need to write a test for this. Will try to finish it over the weekend.

Thanks!

**Comment by Izhaki** [comment]
PS. yarn link should work.

In your local folder root (on nodemon-webpack-plugin) run:

```
yarn link
```

It will tell you how to link it on the consuming package. Should be:

```
yarn link "nodemon-webpack-plugin"
```

**Comment by cellis** [comment]
@Izhaki the linked Typescript repo is currently broken. If you fix it by changing `const arr = 'f';` to a number, it will work and start the server. But if you then break it again, the server remains running. I was hoping this change would stop the server to provide a better developer experience. ( or maybe the dev could pass a flag to nodemon plugin for what they want to do ).

Thanks for looking at this so promptly!

**Comment by Izhaki** [comment]
I do wonder...

If it was alright to begin with, monitoring will start.
If it then breaks, files shouldn't be emitted, so the old server should still be monitored no?
Isn't that the correct behaviour?

**Comment by cellis** [comment]
@Izhaki There are merits to both approaches. I tend to have my terminal running in the background and therefore miss the server breaking. I’d prefer the server to just break instead of giving me false confidence.

**Comment by Izhaki** [comment]
I had a look at your repo. A bit odd Webpack still emit despite the error - couldn't quite figure out why.

I get what you're saying, but there's a larger issue here:

If I am to stop the monitoring on error, I'm diverging from the behaviour you'd get had you not used this plugin (and just install and run nodemon yourself). That may not sound like a big deal to you, but is actually a design principal behind the plugin.

If I am to provide an option with regards to this - it's a breaking API change.

So I'm kind of inclined to keep things as they are.

(one thing is, by using your repo, I saw that the message the plugin logs in such case is incorrect - this will need fixing).

> I tend to have my terminal running in the background and therefore miss the server breaking. 

Have a look at [webpack-notifier](https://www.npmjs.com/package/webpack-notifier)?

**Comment by cellis** [comment]
@Izhaki sounds good. Fwiw, I figured out that setting `noEmitOnError: true` in `tsconfig.json` makes the build break with the ts-loader.

**Pull request closed without merging**
